### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [netioproducts/PyNetio#8]
It would be very helpful if you could tag releases as well. This would enable distributions to fetch the source from GitHub instead of Pypi, where with the latest release only a wheel is available.

Thanks

**Comment by fabaff** [comment]
Could you please address this? It's blocking the update of the package at least on NixOS.

**Comment by AdamVerner** [comment]
Hi, sorry for taking so long, i have added the tags for the latest releases e.g.: `v1.0.7` for the latest one. Is that what you expected?

**Comment by fabaff** [comment]
> Is that what you expected?

Yes, thank you.
